# Generated by Django 4.2.5 on 2023-10-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(blank=True, max_length=50, null=True)),
                ('d', models.CharField(blank=True, max_length=50, null=True)),
                ('i', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
