# Generated by Django 4.2.5 on 2023-10-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdb',
            old_name='d',
            new_name='dis',
        ),
        migrations.RenameField(
            model_name='sdb',
            old_name='i',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='sdb',
            old_name='n',
            new_name='name',
        ),
    ]
