# Generated by Django 4.2.5 on 2023-10-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0002_rename_d_sdb_dis_rename_i_sdb_img_rename_n_sdb_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(blank=True, max_length=50, null=True)),
                ('sname', models.CharField(blank=True, max_length=50, null=True)),
                ('sdis', models.CharField(blank=True, max_length=50, null=True)),
                ('spr', models.IntegerField(blank=True, null=True)),
                ('sim', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
