# Generated by Django 4.2 on 2023-11-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_redb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cadb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctn', models.CharField(blank=True, max_length=50, null=True)),
                ('ctp', models.IntegerField(blank=True, null=True)),
                ('ctq', models.IntegerField(blank=True, null=True)),
                ('ctt', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
